# fly.toml app configuration file generated for aelfgpt on 2024-07-28T01:11:21Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'aelfgpt'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
