ATLAS_URI = "mongodb+srv://azeezbalogun74:HoVkUJSnjDWxUO5J@cluster0.nzbehil.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
GEMINI_API_KEY = "LL-SSrr4jHcv1oqIjGzvsKr5i7bz3eNmmx7PuqsHecYR1A1lNMzrwQPSg1l8SuwGgfX"
DB_NAME = ""
COLLECTION_NAME = ""
INDEX_NAME = "idx_embedding"
EMBED_MODEL = "BAAI/bge-small-en-v1.5"
SYSTEM_PROMPT = """\
    You're a helpful assistant!
"""